branches:

  generator: branch_generator

  frequency: daily

  records: 50

  landing_folder: branches

customers:

  generator: customer_generator

  frequency: daily

  records: 1000

  landing_folder: customers

accounts:

  generator: account_generator

  frequency: daily

  records: 1500

  landing_folder: accounts

cards:

  generator: card_generator

  frequency: daily

  records: 1200

  landing_folder: cards

loans:

  generator: loan_generator

  frequency: daily

  records: 500

  landing_folder: loans

customer_kyc:

  generator: kyc_generator

  frequency: daily

  records: 1000

  landing_folder: customer_kyc

exchange_rates:

  generator: exchange_rate_generator

  frequency: daily

  records: 25

  landing_folder: exchange_rates

transactions:

  generator: transaction_generator

  frequency: 5min

  records: 500

  landing_folder: transactions

atm_transactions:

  generator: atm_generator

  frequency: 5min

  records: 300

  landing_folder: atm_transactions

login_activity:

  generator: login_generator

  frequency: 1min

  records: 200

  landing_folder: login_activity