from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

OUTPUT_FOLDER = PROJECT_ROOT / "output"

CUSTOMER_FOLDER = OUTPUT_FOLDER / "customers"

ACCOUNT_FOLDER = OUTPUT_FOLDER / "accounts"

TRANSACTION_FOLDER = OUTPUT_FOLDER / "transactions"

CARD_FOLDER = OUTPUT_FOLDER / "cards"

LOAN_FOLDER = OUTPUT_FOLDER / "loans"

ATM_FOLDER = OUTPUT_FOLDER / "atm"

LOGIN_FOLDER = OUTPUT_FOLDER / "login"

BRANCH_FOLDER = OUTPUT_FOLDER / "branches"

KYC_FOLDER = OUTPUT_FOLDER / "kyc"

EXCHANGE_FOLDER = OUTPUT_FOLDER / "exchange_rates"


ALL_OUTPUT_FOLDERS = [
    CUSTOMER_FOLDER,
    ACCOUNT_FOLDER,
    TRANSACTION_FOLDER,
    CARD_FOLDER,
    LOAN_FOLDER,
    ATM_FOLDER,
    LOGIN_FOLDER,
    BRANCH_FOLDER,
    KYC_FOLDER,
    EXCHANGE_FOLDER
]